#!/usr/bin/env python3
"""ouroboros.

  tier 0  reference_pattern()   the eight-line implementation, kept as the
          oracle every other tier is differentially tested against.

  tier 1  GSL-1                 a declarative glyph language with a lexer,
          recursive-descent parser, AST, semantic analyser, bytecode compiler
          and a stack virtual machine.  The glyph is no longer drawn; it is
          the result of evaluating a program, whose two canonical strokes are
          closed under a cyclic rotation group generated by matrix
          multiplication and verified against the group axioms.

  tier 2  LLVM                  a backend lowering that bytecode to LLVM IR,
          which verifies, JITs, and links to a native ELF binary.

  tier 3  GSL-2                 a second language, general enough to write a
          compiler in, plus a compiler for it written in itself.  A Python
          seed compiles it once; from then on it compiles its own source, and
          the build is proven correct by a three-generation fixpoint: the
          compiler's output on its own source stops changing.

    python3 ouroboros.py                 render via the virtual machine
    python3 ouroboros.py --emit-llvm     lower the program to LLVM IR
    python3 ouroboros.py --jit           JIT-execute that IR
    python3 ouroboros.py --bootstrap     run the full self-hosting bootstrap
    python3 ouroboros.py --selftest      differential-test every tier

"""

from __future__ import annotations

import abc
import argparse
import enum
import functools
import inspect
import itertools
import logging
import operator
import os
import shutil
import string
import subprocess
import sys
import tempfile
import time
import typing
import weakref
from concurrent.futures import ThreadPoolExecutor
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path
from typing import (
    Any,
    Callable,
    ClassVar,
    Final,
    FrozenSet,
    Generic,
    Iterable,
    Iterator,
    Mapping,
    MutableMapping,
    Protocol,
    Sequence,
    TypeVar,
    runtime_checkable,
)


# ======================================================================
# Tier 0: the reference implementation
# ======================================================================


def reference_pattern(order: int = 7) -> str:
    m = order // 2
    return "\n".join(
        " ".join(
            "*"
            if m in (r, c)
            or (r == 0 and c > m)
            or (c == 0 and r < m)
            or (r == order - 1 and c < m)
            or (c == order - 1 and r > m)
            else " "
            for c in range(order)
        ).rstrip()
        for r in range(order)
    )


__all__ = [
    "GlyphPlatformError",
    "LexicalError",
    "SyntaxError_",
    "SemanticError",
    "CodeGenerationError",
    "ExecutionFault",
    "GroupAxiomViolation",
    "Result",
    "Ok",
    "Err",
    "Coordinate",
    "LinearOperator",
    "RotationGroup",
    "GlyphVirtualMachine",
    "ServiceContainer",
    "synthesize",
    "main",
]

_LOGGER: Final[logging.Logger] = logging.getLogger("glyph.platform")
_LOGGER.addHandler(logging.NullHandler())

_T = TypeVar("_T")
_U = TypeVar("_U")
_E = TypeVar("_E", bound=BaseException)
_NodeT = TypeVar("_NodeT", bound="AstNode")

DEFAULT_LATTICE_ORDER: Final[int] = 7
QUARTER_TURN_CARDINALITY: Final[int] = 4
RASTERIZATION_PARALLELISM_CEILING: Final[int] = 32

CANONICAL_GSL_TEMPLATE: Final[string.Template] = string.Template(
    """
    # ------------------------------------------------------------------
    # Canonical glyph specification, GSL revision 1.
    # ------------------------------------------------------------------
    lattice order $order ;
    symmetry cyclic 4 about centroid ;

    stroke spine = column at apothem span zero .. extremum ;
    stroke limb  = row    at zero    span apothem + 1 .. extremum ;

    emit spine ;
    emit limb ;
    """
)


# ======================================================================
# Layer -1: diagnostics
# ======================================================================


class GlyphPlatformError(Exception):
    """Root of the platform-wide diagnostic hierarchy."""


class LexicalError(GlyphPlatformError):
    """The finite-state transducer entered a rejecting configuration."""


class SyntaxError_(GlyphPlatformError):
    """The token stream is not a sentence of the GSL grammar."""


class SemanticError(GlyphPlatformError):
    """The syntax tree is well formed but not well typed or not well scoped."""


class CodeGenerationError(GlyphPlatformError):
    """Lowering to the GVM instruction set could not be completed."""


class ExecutionFault(GlyphPlatformError):
    """The virtual machine encountered an unrecoverable runtime condition."""


class GroupAxiomViolation(GlyphPlatformError):
    """The generated operator set failed verification as an algebraic group."""


class ResolutionFailure(GlyphPlatformError):
    """The inversion-of-control container could not satisfy a dependency."""


# ======================================================================
# Layer 0: monadic error propagation
# ======================================================================


class Result(Generic[_T], abc.ABC):
    """Discriminated union modelling a computation that may have failed."""

    __slots__ = ()

    @abc.abstractmethod
    def map(self, morphism: Callable[[_T], _U]) -> "Result[_U]": ...

    @abc.abstractmethod
    def and_then(self, arrow: Callable[[_T], "Result[_U]"]) -> "Result[_U]": ...

    @abc.abstractmethod
    def unwrap_or_raise(self) -> _T: ...

    @property
    @abc.abstractmethod
    def is_ok(self) -> bool: ...

    @staticmethod
    def attempt(thunk: Callable[[], _T]) -> "Result[_T]":
        try:
            return Ok(thunk())
        except GlyphPlatformError as exc:
            return Err(exc)


@dataclass(frozen=True, slots=True)
class Ok(Result[_T]):
    """The successful inhabitant of :class:`Result`."""

    value: _T

    def map(self, morphism: Callable[[_T], _U]) -> Result[_U]:
        return Result.attempt(lambda: morphism(self.value))

    def and_then(self, arrow: Callable[[_T], Result[_U]]) -> Result[_U]:
        return arrow(self.value)

    def unwrap_or_raise(self) -> _T:
        return self.value

    @property
    def is_ok(self) -> bool:
        return True


@dataclass(frozen=True, slots=True)
class Err(Result[_T]):
    """The failed inhabitant of :class:`Result`."""

    failure: GlyphPlatformError

    def map(self, morphism: Callable[[_T], _U]) -> Result[_U]:
        return Err(self.failure)

    def and_then(self, arrow: Callable[[_T], Result[_U]]) -> Result[_U]:
        return Err(self.failure)

    def unwrap_or_raise(self) -> _T:
        raise self.failure

    @property
    def is_ok(self) -> bool:
        return False


def instrumented(callable_: Callable[..., _T]) -> Callable[..., _T]:
    """Decorator emitting structured entry and exit telemetry."""

    @functools.wraps(callable_)
    def _wrapper(*args: Any, **kwargs: Any) -> _T:
        started = time.perf_counter()
        _LOGGER.debug("enter %s", callable_.__qualname__)
        try:
            return callable_(*args, **kwargs)
        finally:
            _LOGGER.debug(
                "exit  %s (%.6fs)", callable_.__qualname__, time.perf_counter() - started
            )

    return _wrapper


# ======================================================================
# Layer 1: geometry and linear algebra
# ======================================================================


class Coordinate:
    """Interned, immutable ordinate pair in row-major lattice space (flyweight)."""

    __slots__ = ("row", "column", "__weakref__")
    __match_args__ = ("row", "column")

    _pool: ClassVar[MutableMapping[tuple[int, int], "Coordinate"]] = (
        weakref.WeakValueDictionary()
    )

    def __new__(cls, row: int, column: int) -> "Coordinate":
        key = (row, column)
        interned = cls._pool.get(key)
        if interned is not None:
            return interned
        instance = super().__new__(cls)
        object.__setattr__(instance, "row", row)
        object.__setattr__(instance, "column", column)
        cls._pool[key] = instance
        return instance

    def __setattr__(self, name: str, value: Any) -> None:
        raise AttributeError(f"{type(self).__name__} is immutable")

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Coordinate):
            return NotImplemented
        return self.row == other.row and self.column == other.column

    def __hash__(self) -> int:
        return hash((self.row, self.column))

    def __lt__(self, other: "Coordinate") -> bool:
        return (self.row, self.column) < (other.row, other.column)

    def __repr__(self) -> str:
        return f"Coordinate({self.row}, {self.column})"

    def translated(self, delta: "Coordinate") -> "Coordinate":
        return Coordinate(self.row + delta.row, self.column + delta.column)

    def negated(self) -> "Coordinate":
        return Coordinate(-self.row, -self.column)


@dataclass(frozen=True, slots=True)
class LinearOperator:
    """A 2x2 endomorphism of the integer plane, in row-major component order."""

    a: int
    b: int
    c: int
    d: int

    IDENTITY: ClassVar["LinearOperator"]

    def __matmul__(self, other: "LinearOperator") -> "LinearOperator":
        return LinearOperator(
            self.a * other.a + self.b * other.c,
            self.a * other.b + self.b * other.d,
            self.c * other.a + self.d * other.c,
            self.c * other.b + self.d * other.d,
        )

    def __call__(self, vector: Coordinate) -> Coordinate:
        return Coordinate(
            self.a * vector.row + self.b * vector.column,
            self.c * vector.row + self.d * vector.column,
        )

    @property
    def determinant(self) -> int:
        return self.a * self.d - self.b * self.c

    def conjugated_about(
        self, pivot: Coordinate
    ) -> Callable[[Coordinate], Coordinate]:
        def _affine(point: Coordinate) -> Coordinate:
            return self(point.translated(pivot.negated())).translated(pivot)

        return _affine


LinearOperator.IDENTITY = LinearOperator(1, 0, 0, 1)

QUARTER_TURN_GENERATOR: Final[LinearOperator] = LinearOperator(0, 1, -1, 0)


@dataclass(frozen=True, slots=True)
class RotationGroup:
    """A finite operator group obtained by closure of a generator set."""

    pivot: Coordinate
    elements: tuple[LinearOperator, ...]

    @classmethod
    @instrumented
    def generated_by(
        cls,
        generator: LinearOperator,
        pivot: Coordinate,
        expected_order: int = QUARTER_TURN_CARDINALITY,
    ) -> "RotationGroup":
        accumulated: list[LinearOperator] = [LinearOperator.IDENTITY]
        seen = {LinearOperator.IDENTITY}
        frontier = LinearOperator.IDENTITY
        for _ in range(expected_order * expected_order):
            frontier = frontier @ generator
            if frontier in seen:
                break
            seen.add(frontier)
            accumulated.append(frontier)
        instance = cls(pivot=pivot, elements=tuple(accumulated))
        instance._verify_axioms(expected_order)
        return instance

    def _verify_axioms(self, expected_order: int) -> None:
        if len(self.elements) != expected_order:
            raise GroupAxiomViolation(
                f"generated group has order {len(self.elements)}, "
                f"expected {expected_order}"
            )
        if LinearOperator.IDENTITY not in self.elements:
            raise GroupAxiomViolation("generated set lacks a neutral element")
        population = set(self.elements)
        for left, right in itertools.product(self.elements, repeat=2):
            if left @ right not in population:
                raise GroupAxiomViolation(f"closure violated by {left!r} @ {right!r}")
        for element in self.elements:
            if not any(
                element @ candidate == LinearOperator.IDENTITY
                for candidate in self.elements
            ):
                raise GroupAxiomViolation(f"{element!r} has no inverse in the group")
        for x, y, z in itertools.product(self.elements, repeat=3):
            if (x @ y) @ z != x @ (y @ z):
                raise GroupAxiomViolation("associativity violated")
        _LOGGER.debug("group axioms verified for order %d", expected_order)

    def orbit(self, seed: Coordinate) -> Iterator[Coordinate]:
        return (
            element.conjugated_about(self.pivot)(seed) for element in self.elements
        )

    def close(self, support: Iterable[Coordinate]) -> FrozenSet[Coordinate]:
        return frozenset(
            itertools.chain.from_iterable(self.orbit(point) for point in support)
        )

    def is_invariant(self, support: FrozenSet[Coordinate]) -> bool:
        return all(self.close({point}) <= support for point in support)


# ======================================================================
# Layer 2: lexical analysis
# ======================================================================


class TokenKind(enum.Enum):
    IDENTIFIER = enum.auto()
    INTEGER = enum.auto()
    PLUS = enum.auto()
    MINUS = enum.auto()
    ASSIGN = enum.auto()
    TERMINATOR = enum.auto()
    ELLIPSIS = enum.auto()
    END_OF_STREAM = enum.auto()


class TransducerState(enum.Enum):
    AWAITING_LEXEME = enum.auto()
    ACCUMULATING_IDENTIFIER = enum.auto()
    ACCUMULATING_INTEGER = enum.auto()
    DISCARDING_COMMENT = enum.auto()


@dataclass(frozen=True, slots=True)
class SourcePosition:
    line: int
    column: int

    def __str__(self) -> str:
        return f"{self.line}:{self.column}"


@dataclass(frozen=True, slots=True)
class Token:
    kind: TokenKind
    lexeme: str
    position: SourcePosition

    def expect(self, kind: TokenKind, lexeme: str | None = None) -> "Token":
        if self.kind is not kind or (lexeme is not None and self.lexeme != lexeme):
            raise SyntaxError_(
                f"{self.position}: expected {lexeme or kind.name}, found {self.lexeme!r}"
            )
        return self


_PUNCTUATION_ALPHABET: Final[Mapping[str, TokenKind]] = {
    "+": TokenKind.PLUS,
    "-": TokenKind.MINUS,
    "=": TokenKind.ASSIGN,
    ";": TokenKind.TERMINATOR,
}


class FiniteStateTransducer:
    """Deterministic character-driven tokenizer for GSL source text."""

    def __init__(self, source: str) -> None:
        self._source = source
        self._state = TransducerState.AWAITING_LEXEME

    @instrumented
    def tokenize(self) -> tuple[Token, ...]:
        emitted: list[Token] = []
        buffer: list[str] = []
        anchor = SourcePosition(1, 1)
        line, column = 1, 1
        index = 0
        source = self._source + "\n"

        while index < len(source):
            character = source[index]
            here = SourcePosition(line, column)

            match self._state:
                case TransducerState.DISCARDING_COMMENT:
                    if character == "\n":
                        self._state = TransducerState.AWAITING_LEXEME

                case TransducerState.ACCUMULATING_IDENTIFIER:
                    if character.isalnum() or character == "_":
                        buffer.append(character)
                    else:
                        emitted.append(
                            Token(TokenKind.IDENTIFIER, "".join(buffer), anchor)
                        )
                        buffer.clear()
                        self._state = TransducerState.AWAITING_LEXEME
                        continue

                case TransducerState.ACCUMULATING_INTEGER:
                    if character.isdigit():
                        buffer.append(character)
                    else:
                        emitted.append(
                            Token(TokenKind.INTEGER, "".join(buffer), anchor)
                        )
                        buffer.clear()
                        self._state = TransducerState.AWAITING_LEXEME
                        continue

                case TransducerState.AWAITING_LEXEME:
                    if character == "#":
                        self._state = TransducerState.DISCARDING_COMMENT
                    elif character.isspace():
                        pass
                    elif character.isalpha() or character == "_":
                        anchor = here
                        buffer.append(character)
                        self._state = TransducerState.ACCUMULATING_IDENTIFIER
                    elif character.isdigit():
                        anchor = here
                        buffer.append(character)
                        self._state = TransducerState.ACCUMULATING_INTEGER
                    elif character == ".":
                        if source[index : index + 2] != "..":
                            raise LexicalError(f"{here}: solitary '.' is not a lexeme")
                        emitted.append(Token(TokenKind.ELLIPSIS, "..", here))
                        index += 1
                        column += 1
                    elif character in _PUNCTUATION_ALPHABET:
                        emitted.append(
                            Token(_PUNCTUATION_ALPHABET[character], character, here)
                        )
                    else:
                        raise LexicalError(f"{here}: unexpected character {character!r}")

            if character == "\n":
                line, column = line + 1, 1
            else:
                column += 1
            index += 1

        emitted.append(
            Token(TokenKind.END_OF_STREAM, "<eof>", SourcePosition(line, column))
        )
        return tuple(emitted)


# ======================================================================
# Layer 3: abstract syntax
# ======================================================================


class Orientation(enum.Enum):
    ROW = "row"
    COLUMN = "column"


class AstVisitor(Generic[_T], abc.ABC):
    """Double-dispatch visitor over the GSL abstract syntax tree."""

    @abc.abstractmethod
    def visit_program(self, node: "Program") -> _T: ...

    @abc.abstractmethod
    def visit_lattice_declaration(self, node: "LatticeDeclaration") -> _T: ...

    @abc.abstractmethod
    def visit_symmetry_declaration(self, node: "SymmetryDeclaration") -> _T: ...

    @abc.abstractmethod
    def visit_stroke_declaration(self, node: "StrokeDeclaration") -> _T: ...

    @abc.abstractmethod
    def visit_emit_statement(self, node: "EmitStatement") -> _T: ...

    @abc.abstractmethod
    def visit_integer_literal(self, node: "IntegerLiteral") -> _T: ...

    @abc.abstractmethod
    def visit_symbol_reference(self, node: "SymbolReference") -> _T: ...

    @abc.abstractmethod
    def visit_binary_operation(self, node: "BinaryOperation") -> _T: ...

    @abc.abstractmethod
    def visit_span(self, node: "Span") -> _T: ...


class AstNode(abc.ABC):
    __slots__ = ()

    @abc.abstractmethod
    def accept(self, visitor: AstVisitor[_T]) -> _T: ...

    def children(self) -> Iterator["AstNode"]:
        for value in (getattr(self, slot, None) for slot in self._slot_names()):
            if isinstance(value, AstNode):
                yield value
            elif isinstance(value, tuple):
                yield from (item for item in value if isinstance(item, AstNode))

    @classmethod
    def _slot_names(cls) -> tuple[str, ...]:
        return tuple(
            itertools.chain.from_iterable(
                getattr(base, "__slots__", ()) for base in cls.__mro__
            )
        )


@dataclass(frozen=True, slots=True)
class IntegerLiteral(AstNode):
    value: int

    def accept(self, visitor: AstVisitor[_T]) -> _T:
        return visitor.visit_integer_literal(self)


@dataclass(frozen=True, slots=True)
class SymbolReference(AstNode):
    name: str

    def accept(self, visitor: AstVisitor[_T]) -> _T:
        return visitor.visit_symbol_reference(self)


@dataclass(frozen=True, slots=True)
class BinaryOperation(AstNode):
    operator_token: TokenKind
    left: AstNode
    right: AstNode

    def accept(self, visitor: AstVisitor[_T]) -> _T:
        return visitor.visit_binary_operation(self)


@dataclass(frozen=True, slots=True)
class Span(AstNode):
    lower: AstNode
    upper: AstNode

    def accept(self, visitor: AstVisitor[_T]) -> _T:
        return visitor.visit_span(self)


@dataclass(frozen=True, slots=True)
class LatticeDeclaration(AstNode):
    order: int

    def accept(self, visitor: AstVisitor[_T]) -> _T:
        return visitor.visit_lattice_declaration(self)


@dataclass(frozen=True, slots=True)
class SymmetryDeclaration(AstNode):
    cardinality: int
    pivot: str

    def accept(self, visitor: AstVisitor[_T]) -> _T:
        return visitor.visit_symmetry_declaration(self)


@dataclass(frozen=True, slots=True)
class StrokeDeclaration(AstNode):
    name: str
    orientation: Orientation
    index: AstNode
    span: Span

    def accept(self, visitor: AstVisitor[_T]) -> _T:
        return visitor.visit_stroke_declaration(self)


@dataclass(frozen=True, slots=True)
class EmitStatement(AstNode):
    name: str

    def accept(self, visitor: AstVisitor[_T]) -> _T:
        return visitor.visit_emit_statement(self)


@dataclass(frozen=True, slots=True)
class Program(AstNode):
    declarations: tuple[AstNode, ...]

    def accept(self, visitor: AstVisitor[_T]) -> _T:
        return visitor.visit_program(self)


# ======================================================================
# Layer 4: syntactic analysis
# ======================================================================


class RecursiveDescentParser:
    """LL(1) recursive-descent parser with precedence climbing for arithmetic."""

    def __init__(self, tokens: Sequence[Token]) -> None:
        self._tokens = tokens
        self._cursor = 0

    def _peek(self, offset: int = 0) -> Token:
        return self._tokens[min(self._cursor + offset, len(self._tokens) - 1)]

    def _advance(self) -> Token:
        token = self._peek()
        self._cursor += 1
        return token

    def _consume(self, kind: TokenKind, lexeme: str | None = None) -> Token:
        return self._advance().expect(kind, lexeme)

    def _at_keyword(self, lexeme: str) -> bool:
        token = self._peek()
        return token.kind is TokenKind.IDENTIFIER and token.lexeme == lexeme

    @instrumented
    def parse(self) -> Program:
        declarations: list[AstNode] = []
        while self._peek().kind is not TokenKind.END_OF_STREAM:
            declarations.append(self._parse_declaration())
        return Program(tuple(declarations))

    def _parse_declaration(self) -> AstNode:
        head = self._peek()
        match head.lexeme:
            case "lattice":
                node = self._parse_lattice()
            case "symmetry":
                node = self._parse_symmetry()
            case "stroke":
                node = self._parse_stroke()
            case "emit":
                node = self._parse_emit()
            case _:
                raise SyntaxError_(
                    f"{head.position}: unknown declaration head {head.lexeme!r}"
                )
        self._consume(TokenKind.TERMINATOR)
        return node

    def _parse_lattice(self) -> LatticeDeclaration:
        self._consume(TokenKind.IDENTIFIER, "lattice")
        self._consume(TokenKind.IDENTIFIER, "order")
        return LatticeDeclaration(int(self._consume(TokenKind.INTEGER).lexeme))

    def _parse_symmetry(self) -> SymmetryDeclaration:
        self._consume(TokenKind.IDENTIFIER, "symmetry")
        self._consume(TokenKind.IDENTIFIER, "cyclic")
        cardinality = int(self._consume(TokenKind.INTEGER).lexeme)
        self._consume(TokenKind.IDENTIFIER, "about")
        return SymmetryDeclaration(cardinality, self._consume(TokenKind.IDENTIFIER).lexeme)

    def _parse_stroke(self) -> StrokeDeclaration:
        self._consume(TokenKind.IDENTIFIER, "stroke")
        name = self._consume(TokenKind.IDENTIFIER).lexeme
        self._consume(TokenKind.ASSIGN)
        orientation_token = self._consume(TokenKind.IDENTIFIER)
        try:
            orientation = Orientation(orientation_token.lexeme)
        except ValueError as exc:
            raise SyntaxError_(
                f"{orientation_token.position}: {orientation_token.lexeme!r} "
                f"is not an orientation"
            ) from exc
        self._consume(TokenKind.IDENTIFIER, "at")
        index = self._parse_expression()
        self._consume(TokenKind.IDENTIFIER, "span")
        lower = self._parse_expression()
        self._consume(TokenKind.ELLIPSIS)
        upper = self._parse_expression()
        return StrokeDeclaration(name, orientation, index, Span(lower, upper))

    def _parse_emit(self) -> EmitStatement:
        self._consume(TokenKind.IDENTIFIER, "emit")
        return EmitStatement(self._consume(TokenKind.IDENTIFIER).lexeme)

    def _parse_expression(self) -> AstNode:
        node = self._parse_atom()
        while self._peek().kind in (TokenKind.PLUS, TokenKind.MINUS):
            operator_token = self._advance().kind
            node = BinaryOperation(operator_token, node, self._parse_atom())
        return node

    def _parse_atom(self) -> AstNode:
        token = self._advance()
        match token.kind:
            case TokenKind.INTEGER:
                return IntegerLiteral(int(token.lexeme))
            case TokenKind.IDENTIFIER:
                return SymbolReference(token.lexeme)
            case _:
                raise SyntaxError_(f"{token.position}: expected an atom, got {token.lexeme!r}")


# ======================================================================
# Layer 5: semantic analysis
# ======================================================================


INTRINSIC_SYMBOLS: Final[frozenset[str]] = frozenset(
    {"zero", "apothem", "extremum", "magnitude"}
)


class LexicalScope:
    """A chained symbol table supporting shadowing and parent delegation."""

    def __init__(self, parent: "LexicalScope | None" = None) -> None:
        self._parent = parent
        self._bindings: dict[str, Any] = {}

    def declare(self, name: str, payload: Any) -> None:
        if name in self._bindings:
            raise SemanticError(f"symbol {name!r} redeclared in the same scope")
        self._bindings[name] = payload

    def lookup(self, name: str) -> Any:
        scope: LexicalScope | None = self
        while scope is not None:
            if name in scope._bindings:
                return scope._bindings[name]
            scope = scope._parent
        raise SemanticError(f"unresolved symbol {name!r}")

    def descend(self) -> "LexicalScope":
        return LexicalScope(self)


@dataclass(slots=True)
class SemanticModel:
    """The analysis product handed to the lowering phase."""

    order: int = DEFAULT_LATTICE_ORDER
    symmetry_cardinality: int = QUARTER_TURN_CARDINALITY
    pivot: str = "centroid"
    strokes: dict[str, StrokeDeclaration] = field(default_factory=dict)
    emissions: list[str] = field(default_factory=list)


class SemanticAnalyzer(AstVisitor[None]):
    """Validates scoping, arity, parity and reachability across the tree."""

    def __init__(self) -> None:
        self.model = SemanticModel()
        self._scope = LexicalScope()
        for intrinsic in sorted(INTRINSIC_SYMBOLS):
            self._scope.declare(intrinsic, "intrinsic")

    @instrumented
    def analyze(self, program: Program) -> SemanticModel:
        program.accept(self)
        if not self.model.emissions:
            raise SemanticError("program emits no strokes; glyph would be vacuous")
        return self.model

    def visit_program(self, node: Program) -> None:
        for declaration in node.declarations:
            declaration.accept(self)

    def visit_lattice_declaration(self, node: LatticeDeclaration) -> None:
        if node.order < 3 or node.order % 2 == 0:
            raise SemanticError(
                f"lattice order must be an odd integer >= 3, received {node.order}"
            )
        self.model.order = node.order

    def visit_symmetry_declaration(self, node: SymmetryDeclaration) -> None:
        if node.pivot != "centroid":
            raise SemanticError(f"unsupported symmetry pivot {node.pivot!r}")
        if node.cardinality < 1:
            raise SemanticError("symmetry cardinality must be positive")
        self.model.symmetry_cardinality = node.cardinality
        self.model.pivot = node.pivot

    def visit_stroke_declaration(self, node: StrokeDeclaration) -> None:
        self._scope.declare(node.name, node)
        inner = self._scope.descend()
        previous, self._scope = self._scope, inner
        try:
            node.index.accept(self)
            node.span.accept(self)
        finally:
            self._scope = previous
        self.model.strokes[node.name] = node

    def visit_emit_statement(self, node: EmitStatement) -> None:
        binding = self._scope.lookup(node.name)
        if not isinstance(binding, StrokeDeclaration):
            raise SemanticError(f"{node.name!r} is not emittable")
        self.model.emissions.append(node.name)

    def visit_integer_literal(self, node: IntegerLiteral) -> None:
        return None

    def visit_symbol_reference(self, node: SymbolReference) -> None:
        if node.name not in INTRINSIC_SYMBOLS:
            raise SemanticError(f"{node.name!r} is not an intrinsic lattice symbol")

    def visit_binary_operation(self, node: BinaryOperation) -> None:
        node.left.accept(self)
        node.right.accept(self)

    def visit_span(self, node: Span) -> None:
        node.lower.accept(self)
        node.upper.accept(self)


# ======================================================================
# Layer 6: the GVM instruction set
# ======================================================================


class Instruction(abc.ABC):
    """Base of the Glyph Virtual Machine instruction set architecture."""

    _opcode_table: ClassVar[dict[str, int]] = {}
    opcode: ClassVar[int]

    def __init_subclass__(cls, **kwargs: Any) -> None:
        super().__init_subclass__(**kwargs)
        cls.opcode = len(Instruction._opcode_table)
        Instruction._opcode_table[cls.__name__] = cls.opcode

    def disassemble(self) -> str:
        operands = " ".join(
            f"{key}={value!r}" for key, value in vars(self).items()
        )
        return f"{self.opcode:>3}  {type(self).__name__:<20} {operands}"


@dataclass(frozen=True)
class PushConstant(Instruction):
    value: int


@dataclass(frozen=True)
class LoadIntrinsic(Instruction):
    name: str


@dataclass(frozen=True)
class BinaryAdd(Instruction):
    pass


@dataclass(frozen=True)
class BinarySubtract(Instruction):
    pass


@dataclass(frozen=True)
class MakeInterval(Instruction):
    pass


@dataclass(frozen=True)
class EmitOrientedRun(Instruction):
    orientation: Orientation


@dataclass(frozen=True)
class CloseUnderGroup(Instruction):
    pass


@dataclass(frozen=True)
class Halt(Instruction):
    pass


@dataclass(frozen=True, slots=True)
class ObjectModule:
    """A linked, immutable unit of GVM object code plus its static metadata."""

    instructions: tuple[Instruction, ...]
    order: int
    symmetry_cardinality: int

    def disassembly(self) -> str:
        return "\n".join(
            f"{address:04d}  {instruction.disassemble()}"
            for address, instruction in enumerate(self.instructions)
        )


class BytecodeEmitter(AstVisitor[None]):
    """Lowers a validated syntax tree into linear GVM object code."""

    def __init__(self, model: SemanticModel) -> None:
        self._model = model
        self._buffer: list[Instruction] = []

    @instrumented
    def lower(self, program: Program) -> ObjectModule:
        program.accept(self)
        self._buffer.append(CloseUnderGroup())
        self._buffer.append(Halt())
        if not any(isinstance(item, EmitOrientedRun) for item in self._buffer):
            raise CodeGenerationError("lowering produced no emission instructions")
        return ObjectModule(
            instructions=tuple(self._buffer),
            order=self._model.order,
            symmetry_cardinality=self._model.symmetry_cardinality,
        )

    def visit_program(self, node: Program) -> None:
        for declaration in node.declarations:
            declaration.accept(self)

    def visit_lattice_declaration(self, node: LatticeDeclaration) -> None:
        return None

    def visit_symmetry_declaration(self, node: SymmetryDeclaration) -> None:
        return None

    def visit_stroke_declaration(self, node: StrokeDeclaration) -> None:
        return None

    def visit_emit_statement(self, node: EmitStatement) -> None:
        stroke = self._model.strokes[node.name]
        stroke.index.accept(self)
        stroke.span.accept(self)
        self._buffer.append(EmitOrientedRun(stroke.orientation))

    def visit_integer_literal(self, node: IntegerLiteral) -> None:
        self._buffer.append(PushConstant(node.value))

    def visit_symbol_reference(self, node: SymbolReference) -> None:
        self._buffer.append(LoadIntrinsic(node.name))

    def visit_binary_operation(self, node: BinaryOperation) -> None:
        node.left.accept(self)
        node.right.accept(self)
        self._buffer.append(
            BinaryAdd() if node.operator_token is TokenKind.PLUS else BinarySubtract()
        )

    def visit_span(self, node: Span) -> None:
        node.lower.accept(self)
        node.upper.accept(self)
        self._buffer.append(MakeInterval())


# ======================================================================
# Layer 7: the virtual machine
# ======================================================================


@dataclass(frozen=True, slots=True)
class EmissionCommand:
    """Undoable mutation of the canvas support set (command pattern)."""

    cells: FrozenSet[Coordinate]

    def apply(self, canvas: set[Coordinate]) -> None:
        canvas |= self.cells

    def revert(self, canvas: set[Coordinate]) -> None:
        canvas -= self.cells


class EmissionJournal:
    """Append-only journal granting transactional rollback over emissions."""

    def __init__(self) -> None:
        self._entries: list[EmissionCommand] = []

    def record(self, command: EmissionCommand, canvas: set[Coordinate]) -> None:
        command.apply(canvas)
        self._entries.append(command)

    def rollback(self, canvas: set[Coordinate]) -> None:
        while self._entries:
            self._entries.pop().revert(canvas)

    def __len__(self) -> int:
        return len(self._entries)


class GlyphVirtualMachine:
    """A stack machine executing GVM object code over a lattice canvas."""

    def __init__(self, module: ObjectModule) -> None:
        self._module = module
        self._stack: list[Any] = []
        self._canvas: set[Coordinate] = set()
        self._journal = EmissionJournal()
        self._program_counter = 0
        self._apothem = module.order // 2
        self._group = RotationGroup.generated_by(
            QUARTER_TURN_GENERATOR,
            Coordinate(self._apothem, self._apothem),
            module.symmetry_cardinality,
        )
        self._intrinsics: Mapping[str, int] = {
            "zero": 0,
            "apothem": self._apothem,
            "extremum": module.order - 1,
            "magnitude": module.order,
        }

    @contextmanager
    def _transaction(self) -> Iterator[None]:
        try:
            yield
        except Exception:
            self._journal.rollback(self._canvas)
            raise

    @instrumented
    def run(self) -> FrozenSet[Coordinate]:
        with self._transaction():
            while True:
                if self._program_counter >= len(self._module.instructions):
                    raise ExecutionFault("program counter ran off the end of the module")
                instruction = self._module.instructions[self._program_counter]
                self._program_counter += 1
                if isinstance(instruction, Halt):
                    break
                self._execute(instruction)
            if self._stack:
                raise ExecutionFault(f"operand stack not drained: {self._stack!r}")
        return frozenset(self._canvas)

    def _pop(self) -> Any:
        try:
            return self._stack.pop()
        except IndexError as exc:
            raise ExecutionFault("operand stack underflow") from exc

    @functools.singledispatchmethod
    def _execute(self, instruction: Instruction) -> None:
        raise ExecutionFault(f"illegal instruction {instruction!r}")

    @_execute.register(PushConstant)
    def _(self, instruction: PushConstant) -> None:
        self._stack.append(instruction.value)

    @_execute.register(LoadIntrinsic)
    def _(self, instruction: LoadIntrinsic) -> None:
        try:
            self._stack.append(self._intrinsics[instruction.name])
        except KeyError as exc:
            raise ExecutionFault(f"unbound intrinsic {instruction.name!r}") from exc

    @_execute.register(BinaryAdd)
    def _(self, instruction: BinaryAdd) -> None:
        right, left = self._pop(), self._pop()
        self._stack.append(operator.add(left, right))

    @_execute.register(BinarySubtract)
    def _(self, instruction: BinarySubtract) -> None:
        right, left = self._pop(), self._pop()
        self._stack.append(operator.sub(left, right))

    @_execute.register(MakeInterval)
    def _(self, instruction: MakeInterval) -> None:
        upper, lower = self._pop(), self._pop()
        if lower > upper:
            raise ExecutionFault(f"degenerate interval [{lower}, {upper}]")
        self._stack.append(range(lower, upper + 1))

    @_execute.register(EmitOrientedRun)
    def _(self, instruction: EmitOrientedRun) -> None:
        interval, index = self._pop(), self._pop()
        factory = (
            (lambda scalar: Coordinate(index, scalar))
            if instruction.orientation is Orientation.ROW
            else (lambda scalar: Coordinate(scalar, index))
        )
        self._journal.record(
            EmissionCommand(frozenset(map(factory, interval))), self._canvas
        )

    @_execute.register(CloseUnderGroup)
    def _(self, instruction: CloseUnderGroup) -> None:
        closure = self._group.close(self._canvas)
        self._journal.record(EmissionCommand(closure), self._canvas)

    @property
    def group(self) -> RotationGroup:
        return self._group


# ======================================================================
# Layer 8: presentation
# ======================================================================


class Ink(enum.Enum):
    OCCUPIED = "*"
    VACANT = " "

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True, slots=True)
class RenderContext:
    order: int
    support: FrozenSet[Coordinate]
    group: RotationGroup


@runtime_checkable
class RasterizationStrategy(Protocol):
    def rasterize(self, context: RenderContext) -> str: ...


@dataclass(frozen=True, slots=True)
class ConcurrentAsteriskRasterizer:
    """Materializes each scanline on a worker thread, then reassembles in order."""

    intercell_delimiter: str = " "
    interline_delimiter: str = "\n"

    def _scanline(self, context: RenderContext, row: int) -> str:
        return self.intercell_delimiter.join(
            str(
                Ink.OCCUPIED
                if Coordinate(row, column) in context.support
                else Ink.VACANT
            )
            for column in range(context.order)
        ).rstrip()

    def rasterize(self, context: RenderContext) -> str:
        workers = min(RASTERIZATION_PARALLELISM_CEILING, max(1, context.order))
        with ThreadPoolExecutor(max_workers=workers) as pool:
            scanlines = pool.map(
                functools.partial(self._scanline, context), range(context.order)
            )
            return self.interline_delimiter.join(scanlines)


@runtime_checkable
class RenderMiddleware(Protocol):
    def __call__(
        self, context: RenderContext, nxt: Callable[[RenderContext], str]
    ) -> str: ...


@dataclass(frozen=True, slots=True)
class TracingMiddleware:
    def __call__(
        self, context: RenderContext, nxt: Callable[[RenderContext], str]
    ) -> str:
        started = time.perf_counter()
        product = nxt(context)
        _LOGGER.debug(
            "rasterized %d cells on a %dx%d lattice in %.6fs",
            len(context.support),
            context.order,
            context.order,
            time.perf_counter() - started,
        )
        return product


@dataclass(frozen=True, slots=True)
class SymmetryInvariantMiddleware:
    """Fails closed if the support set is not stable under the group action."""

    def __call__(
        self, context: RenderContext, nxt: Callable[[RenderContext], str]
    ) -> str:
        if not context.group.is_invariant(context.support):
            raise GlyphPlatformError("support set is not invariant under the group")
        return nxt(context)


@dataclass(frozen=True, slots=True)
class BoundsCheckingMiddleware:
    def __call__(
        self, context: RenderContext, nxt: Callable[[RenderContext], str]
    ) -> str:
        stray = [
            cell
            for cell in context.support
            if not (0 <= cell.row < context.order and 0 <= cell.column < context.order)
        ]
        if stray:
            raise GlyphPlatformError(f"{len(stray)} cells escaped the lattice: {stray[:3]}")
        return nxt(context)


class RenderPipeline:
    """An onion of middleware wrapped around a terminal rasterization strategy."""

    def __init__(
        self,
        strategy: RasterizationStrategy,
        middleware: Sequence[RenderMiddleware] = (),
    ) -> None:
        self._terminal: Callable[[RenderContext], str] = strategy.rasterize
        self._chain = functools.reduce(
            lambda nxt, layer: functools.partial(layer, nxt=nxt),
            reversed(tuple(middleware)),
            self._terminal,
        )

    def __call__(self, context: RenderContext) -> str:
        return self._chain(context)


# ======================================================================
# Layer 9: inversion of control
# ======================================================================


class ServiceContainer:
    """A reflective IoC container resolving constructors by type annotation."""

    def __init__(self) -> None:
        self._providers: dict[type, Callable[["ServiceContainer"], Any]] = {}
        self._singletons: dict[type, Any] = {}

    def register(
        self, interface: type, provider: Callable[["ServiceContainer"], Any]
    ) -> "ServiceContainer":
        self._providers[interface] = provider
        return self

    def register_instance(self, interface: type, instance: Any) -> "ServiceContainer":
        self._singletons[interface] = instance
        return self

    def resolve(self, interface: type) -> Any:
        if interface in self._singletons:
            return self._singletons[interface]
        provider = self._providers.get(interface)
        if provider is None:
            provider = functools.partial(self._autowire, interface)
        instance = provider(self)
        self._singletons[interface] = instance
        return instance

    def _autowire(self, interface: type, _: "ServiceContainer") -> Any:
        try:
            signature = inspect.signature(interface)
            hints = typing.get_type_hints(interface.__init__)
        except (TypeError, NameError) as exc:
            raise ResolutionFailure(f"cannot introspect {interface!r}") from exc
        arguments = {
            name: self.resolve(hints[name])
            for name, parameter in signature.parameters.items()
            if parameter.default is inspect.Parameter.empty and name in hints
        }
        return interface(**arguments)


# ======================================================================
# Layer 10: the LLVM lowering backend
# ======================================================================


class LlvmToolchainUnavailable(GlyphPlatformError):
    """The optional llvmlite binding is not importable in this interpreter."""


class LlvmLoweringError(GlyphPlatformError):
    """The GVM object module could not be lowered to the LLVM IR dialect."""


@dataclass(frozen=True, slots=True)
class TargetProfile:
    """Static description of the machine the IR is being lowered for."""

    triple: str = "x86_64-unknown-linux-gnu"
    identifier: str = "glyph.canonical"
    source_filename: str = "canonical.gsl"


_ORIENTATION_ENCODING: Final[Mapping[Orientation, int]] = {
    Orientation.ROW: 0,
    Orientation.COLUMN: 1,
}

_LLVM_RUNTIME_TEMPLATE: Final[string.Template] = string.Template(
    """
@gvm.canvas = internal global [$CELLS x i8] zeroinitializer
@lattice.zero = internal constant i32 0
@lattice.apothem = internal constant i32 $APOTHEM
@lattice.extremum = internal constant i32 $EXTREMUM
@lattice.magnitude = internal constant i32 $ORDER

declare i32 @putchar(i32)
declare i32 @fflush(ptr)

define internal ptr @gvm.cell(i32 %row, i32 %col) {
entry:
  %o0 = mul nsw i32 %row, $ORDER
  %o1 = add nsw i32 %o0, %col
  %o2 = sext i32 %o1 to i64
  %slot = getelementptr inbounds [$CELLS x i8], ptr @gvm.canvas, i64 0, i64 %o2
  ret ptr %slot
}

define internal void @gvm.emit_run(i32 %index, i32 %lo, i32 %hi, i32 %orient) {
entry:
  %cursor = alloca i32, align 4
  store i32 %lo, ptr %cursor, align 4
  br label %head

head:
  %cur = load i32, ptr %cursor, align 4
  %more = icmp sle i32 %cur, %hi
  br i1 %more, label %body, label %exit

body:
  %scalar = load i32, ptr %cursor, align 4
  %isrow = icmp eq i32 %orient, 0
  %row = select i1 %isrow, i32 %index, i32 %scalar
  %col = select i1 %isrow, i32 %scalar, i32 %index
  %slot = call ptr @gvm.cell(i32 %row, i32 %col)
  store i8 1, ptr %slot, align 1
  %bumped = add nsw i32 %scalar, 1
  store i32 %bumped, ptr %cursor, align 4
  br label %head

exit:
  ret void
}

define internal void @gvm.close_group() {
entry:
  %pass = alloca i32, align 4
  %row = alloca i32, align 4
  %col = alloca i32, align 4
  store i32 0, ptr %pass, align 4
  br label %pass.head

pass.head:
  %p = load i32, ptr %pass, align 4
  %pmore = icmp slt i32 %p, $PASSES
  br i1 %pmore, label %pass.body, label %pass.exit

pass.body:
  store i32 0, ptr %row, align 4
  br label %row.head

row.head:
  %r = load i32, ptr %row, align 4
  %rmore = icmp slt i32 %r, $ORDER
  br i1 %rmore, label %row.body, label %row.exit

row.body:
  store i32 0, ptr %col, align 4
  br label %col.head

col.head:
  %c = load i32, ptr %col, align 4
  %cmore = icmp slt i32 %c, $ORDER
  br i1 %cmore, label %col.body, label %col.exit

col.body:
  %cr = load i32, ptr %row, align 4
  %cc = load i32, ptr %col, align 4
  %src = call ptr @gvm.cell(i32 %cr, i32 %cc)
  %ink = load i8, ptr %src, align 1
  %lit = icmp ne i8 %ink, 0
  br i1 %lit, label %col.mark, label %col.step

col.mark:
  %mr = load i32, ptr %row, align 4
  %mc = load i32, ptr %col, align 4
  %image.column = sub nsw i32 $DIAMETER, %mr
  %dst = call ptr @gvm.cell(i32 %mc, i32 %image.column)
  store i8 1, ptr %dst, align 1
  br label %col.step

col.step:
  %cnow = load i32, ptr %col, align 4
  %cnext = add nsw i32 %cnow, 1
  store i32 %cnext, ptr %col, align 4
  br label %col.head

col.exit:
  %rnow = load i32, ptr %row, align 4
  %rnext = add nsw i32 %rnow, 1
  store i32 %rnext, ptr %row, align 4
  br label %row.head

row.exit:
  %pnow = load i32, ptr %pass, align 4
  %pnext = add nsw i32 %pnow, 1
  store i32 %pnext, ptr %pass, align 4
  br label %pass.head

pass.exit:
  ret void
}

define internal void @gvm.render() {
entry:
  %row = alloca i32, align 4
  %col = alloca i32, align 4
  %last = alloca i32, align 4
  store i32 0, ptr %row, align 4
  br label %row.head

row.head:
  %r = load i32, ptr %row, align 4
  %rmore = icmp slt i32 %r, $ORDER
  br i1 %rmore, label %scan.init, label %row.done

scan.init:
  store i32 -1, ptr %last, align 4
  store i32 0, ptr %col, align 4
  br label %scan.head

scan.head:
  %sc = load i32, ptr %col, align 4
  %smore = icmp slt i32 %sc, $ORDER
  br i1 %smore, label %scan.body, label %scan.exit

scan.body:
  %sr = load i32, ptr %row, align 4
  %sc2 = load i32, ptr %col, align 4
  %sp = call ptr @gvm.cell(i32 %sr, i32 %sc2)
  %sink = load i8, ptr %sp, align 1
  %slit = icmp ne i8 %sink, 0
  br i1 %slit, label %scan.mark, label %scan.step

scan.mark:
  %sc3 = load i32, ptr %col, align 4
  store i32 %sc3, ptr %last, align 4
  br label %scan.step

scan.step:
  %sc4 = load i32, ptr %col, align 4
  %sc5 = add nsw i32 %sc4, 1
  store i32 %sc5, ptr %col, align 4
  br label %scan.head

scan.exit:
  store i32 0, ptr %col, align 4
  br label %print.head

print.head:
  %pc = load i32, ptr %col, align 4
  %lastv = load i32, ptr %last, align 4
  %pmore = icmp sle i32 %pc, %lastv
  br i1 %pmore, label %print.body, label %print.newline

print.body:
  %pc2 = load i32, ptr %col, align 4
  %needsep = icmp sgt i32 %pc2, 0
  br i1 %needsep, label %print.separator, label %print.cell

print.separator:
  %sepres = call i32 @putchar(i32 32)
  br label %print.cell

print.cell:
  %pr = load i32, ptr %row, align 4
  %pc3 = load i32, ptr %col, align 4
  %pp = call ptr @gvm.cell(i32 %pr, i32 %pc3)
  %pink = load i8, ptr %pp, align 1
  %plit = icmp ne i8 %pink, 0
  %glyph = select i1 %plit, i32 42, i32 32
  %cellres = call i32 @putchar(i32 %glyph)
  %pc4 = load i32, ptr %col, align 4
  %pc5 = add nsw i32 %pc4, 1
  store i32 %pc5, ptr %col, align 4
  br label %print.head

print.newline:
  %nlres = call i32 @putchar(i32 10)
  %rn = load i32, ptr %row, align 4
  %rn2 = add nsw i32 %rn, 1
  store i32 %rn2, ptr %row, align 4
  br label %row.head

row.done:
  ret void
}
"""
)


@dataclass(frozen=True, slots=True)
class LlvmModule:
    """A textual LLVM IR translation unit plus its provenance metadata."""

    text: str
    profile: TargetProfile
    order: int

    def __str__(self) -> str:
        return self.text


class _VirtualRegisterAllocator:
    """Monotonic namer guaranteeing uniqueness of SSA value identifiers."""

    def __init__(self, prefix: str = "g") -> None:
        self._prefix = prefix
        self._counter = itertools.count()

    def fresh(self) -> str:
        return f"%{self._prefix}{next(self._counter)}"


class LlvmLoweringBackend:
    """Translates GVM object code into an equivalent LLVM IR translation unit.

    The backend performs abstract interpretation of the operand stack at
    lowering time, materializing each stack slot either as an SSA register
    reference or as a half-open interval descriptor, and emits a call into the
    hand-written IR runtime for every side-effecting instruction.
    """

    def __init__(self, profile: TargetProfile | None = None) -> None:
        self._profile = profile or TargetProfile()

    @instrumented
    def lower(self, module: ObjectModule) -> LlvmModule:
        apothem = module.order // 2
        runtime = _LLVM_RUNTIME_TEMPLATE.substitute(
            ORDER=module.order,
            CELLS=module.order * module.order,
            APOTHEM=apothem,
            EXTREMUM=module.order - 1,
            DIAMETER=2 * apothem,
            PASSES=max(1, module.symmetry_cardinality - 1),
        )
        header = "\n".join(
            (
                f"; ModuleID = '{self._profile.identifier}'",
                f'source_filename = "{self._profile.source_filename}"',
                f'target triple = "{self._profile.triple}"',
            )
        )
        return LlvmModule(
            text="\n".join((header, runtime, self._lower_entry_point(module), "")),
            profile=self._profile,
            order=module.order,
        )

    def _lower_entry_point(self, module: ObjectModule) -> str:
        registers = _VirtualRegisterAllocator()
        stack: list[tuple[str, ...]] = []
        body: list[str] = []

        for instruction in module.instructions:
            match instruction:
                case PushConstant(value=value):
                    stack.append(("scalar", str(value)))
                case LoadIntrinsic(name=name):
                    destination = registers.fresh()
                    body.append(
                        f"  {destination} = load i32, ptr @lattice.{name}, align 4"
                    )
                    stack.append(("scalar", destination))
                case BinaryAdd() | BinarySubtract():
                    right, left = self._pop_scalar(stack), self._pop_scalar(stack)
                    destination = registers.fresh()
                    mnemonic = "add" if isinstance(instruction, BinaryAdd) else "sub"
                    body.append(
                        f"  {destination} = {mnemonic} nsw i32 {left}, {right}"
                    )
                    stack.append(("scalar", destination))
                case MakeInterval():
                    upper, lower = self._pop_scalar(stack), self._pop_scalar(stack)
                    stack.append(("interval", lower, upper))
                case EmitOrientedRun(orientation=orientation):
                    interval = self._pop_interval(stack)
                    index = self._pop_scalar(stack)
                    body.append(
                        f"  call void @gvm.emit_run(i32 {index}, "
                        f"i32 {interval[0]}, i32 {interval[1]}, "
                        f"i32 {_ORIENTATION_ENCODING[orientation]})"
                    )
                case CloseUnderGroup():
                    body.append("  call void @gvm.close_group()")
                case Halt():
                    break
                case _:
                    raise LlvmLoweringError(f"unlowerable instruction {instruction!r}")

        if stack:
            raise LlvmLoweringError(f"abstract stack not drained: {stack!r}")

        body.append("  call void @gvm.render()")
        body.append(f"  {registers.fresh()} = call i32 @fflush(ptr null)")
        body.append("  ret i32 0")
        return "\n".join(("define i32 @main() {", "entry:", *body, "}"))

    @staticmethod
    def _pop_scalar(stack: list[tuple[str, ...]]) -> str:
        if not stack or stack[-1][0] != "scalar":
            raise LlvmLoweringError("expected a scalar on the abstract stack")
        return stack.pop()[1]

    @staticmethod
    def _pop_interval(stack: list[tuple[str, ...]]) -> tuple[str, str]:
        if not stack or stack[-1][0] != "interval":
            raise LlvmLoweringError("expected an interval on the abstract stack")
        _, lower, upper = stack.pop()
        return lower, upper


class LlvmToolchainService:
    """Adapter over the optional llvmlite binding: verify, optimize, JIT, link."""

    @functools.cached_property
    def _binding(self) -> Any:
        try:
            import llvmlite.binding as binding
        except ImportError as exc:
            raise LlvmToolchainUnavailable(
                "llvmlite is not installed; `-emit-llvm` still works, but "
                "verification, optimization, JIT and object emission do not"
            ) from exc
        binding.initialize_native_target()
        binding.initialize_native_asmprinter()
        return binding

    @property
    def version(self) -> str:
        return ".".join(str(part) for part in self._binding.llvm_version_info)

    def _parse(self, module: LlvmModule) -> Any:
        parsed = self._binding.parse_assembly(module.text)
        parsed.verify()
        return parsed

    @instrumented
    def verify(self, module: LlvmModule) -> str:
        self._parse(module)
        return f"LLVM {self.version}: module verified"

    @instrumented
    def optimize(self, module: LlvmModule, level: int = 2) -> LlvmModule:
        binding = self._binding
        parsed = self._parse(module)
        tuning = binding.PipelineTuningOptions(speed_level=level)
        builder = binding.PassBuilder(self._target_machine(), tuning)
        builder.getModulePassManager().run(parsed, builder)
        return LlvmModule(str(parsed), module.profile, module.order)

    def _target_machine(self) -> Any:
        target = self._binding.Target.from_default_triple()
        return target.create_target_machine()

    @instrumented
    def emit_object(self, module: LlvmModule, path: str) -> str:
        machine = self._target_machine()
        with open(path, "wb") as handle:
            handle.write(machine.emit_object(self._parse(module)))
        return path

    @instrumented
    def emit_assembly(self, module: LlvmModule) -> str:
        return self._target_machine().emit_assembly(self._parse(module))

    @instrumented
    def jit_execute(self, module: LlvmModule) -> int:
        import ctypes

        binding = self._binding
        machine = self._target_machine()
        parsed = self._parse(module)
        with binding.create_mcjit_compiler(parsed, machine) as engine:
            engine.finalize_object()
            engine.run_static_constructors()
            entry = engine.get_function_address("main")
            if not entry:
                raise LlvmToolchainUnavailable("JIT could not resolve @main")
            return ctypes.CFUNCTYPE(ctypes.c_int)(entry)()


# ======================================================================
# Layer 11: facade
# ======================================================================


@dataclass(frozen=True, slots=True)
class CompilationArtifacts:
    """Everything the toolchain produced for a single synthesis request."""

    source: str
    tokens: tuple[Token, ...]
    tree: Program
    model: SemanticModel
    module: ObjectModule
    llvm: LlvmModule
    support: FrozenSet[Coordinate]
    rendering: str


@instrumented
def compile_and_execute(source: str) -> CompilationArtifacts:
    """Drives the full front end, back end and presentation pipeline."""
    tokens = FiniteStateTransducer(source).tokenize()
    tree = RecursiveDescentParser(tokens).parse()
    model = SemanticAnalyzer().analyze(tree)
    module = BytecodeEmitter(model).lower(tree)
    machine = GlyphVirtualMachine(module)
    support = machine.run()

    container = ServiceContainer()
    container.register_instance(RasterizationStrategy, ConcurrentAsteriskRasterizer())
    pipeline = RenderPipeline(
        strategy=container.resolve(RasterizationStrategy),
        middleware=(
            TracingMiddleware(),
            BoundsCheckingMiddleware(),
            SymmetryInvariantMiddleware(),
        ),
    )
    context = RenderContext(order=model.order, support=support, group=machine.group)
    return CompilationArtifacts(
        source=source,
        tokens=tokens,
        tree=tree,
        model=model,
        module=module,
        llvm=LlvmLoweringBackend().lower(module),
        support=support,
        rendering=pipeline(context),
    )


def synthesize(order: int = DEFAULT_LATTICE_ORDER) -> Result[CompilationArtifacts]:
    """Facade compiling the canonical specification at the requested order."""
    return Result.attempt(
        lambda: compile_and_execute(
            CANONICAL_GSL_TEMPLATE.substitute(order=order)
        )
    )


# ======================================================================
# driver
# ======================================================================


def _selftest(orders: Sequence[int]) -> int:
    """Differentially test every tier in this file against tier 0."""
    failures = 0
    for order in orders:
        expected = reference_pattern(order)
        artifacts = synthesize(order).unwrap_or_raise()
        tiers = [("gvm", artifacts.rendering)]
        try:
            toolchain = LlvmToolchainService()
            toolchain.verify(artifacts.llvm)
            with tempfile.TemporaryDirectory(prefix="ouroboros-") as scratch:
                binary = link_executable(
                    artifacts.llvm.text, Path(scratch) / "glyph", 2
                )
                tiers.append(("native", _run(binary, "").rstrip("\n")))
        except (LlvmToolchainUnavailable, OSError) as exc:
            print(f"  n={order:<3} llvm tiers skipped: {exc}", file=sys.stderr)
        verdict = "ok"
        for label, produced in tiers:
            if produced != expected:
                verdict = f"MISMATCH in {label}"
                failures = failures + 1
        print(f"  n={order:<3} {' == '.join(['tier0'] + [t for t, _ in tiers])}  {verdict}")
    return 1 if failures else 0


def _parse_arguments(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="ouroboros - the pattern, and everything it grew into",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("-n", "--order", type=int, default=DEFAULT_LATTICE_ORDER)
    parser.add_argument("-v", "--verbose", action="count", default=0)
    parser.add_argument("-S", "--emit-assembly", action="store_true")
    parser.add_argument("-T", "--emit-tokens", action="store_true")

    backend = parser.add_argument_group("LLVM backend")
    backend.add_argument("--emit-llvm", action="store_true")
    backend.add_argument("--emit-native-assembly", action="store_true")
    backend.add_argument("--emit-object", metavar="PATH")
    backend.add_argument("--verify-llvm", action="store_true")
    backend.add_argument("--jit", action="store_true")
    backend.add_argument("-O", "--opt-level", type=int, choices=range(4), default=0)
    backend.add_argument("--triple", default=TargetProfile().triple)

    parser.add_argument("--selftest", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    namespace = _parse_arguments(argv)
    logging.basicConfig(
        level=logging.DEBUG if namespace.verbose else logging.WARNING,
        stream=sys.stderr,
        format="%(levelname)s %(name)s %(message)s",
    )

    if namespace.selftest:
        return _selftest((3, 5, 7, 9, 11, 15, 21))

    outcome = synthesize(namespace.order)
    if not outcome.is_ok:
        print(f"synthesis aborted: {typing.cast(Err, outcome).failure}", file=sys.stderr)
        return 2
    artifacts = outcome.unwrap_or_raise()

    if namespace.emit_tokens:
        for token in artifacts.tokens:
            print(f"{token.position:>8}  {token.kind.name:<14} {token.lexeme!r}", file=sys.stderr)
    if namespace.emit_assembly:
        print(artifacts.module.disassembly(), file=sys.stderr)

    backend_requested = any(
        (
            namespace.emit_llvm,
            namespace.emit_native_assembly,
            namespace.emit_object,
            namespace.verify_llvm,
            namespace.jit,
            namespace.opt_level,
        )
    )
    if not backend_requested:
        sys.stdout.write(artifacts.rendering + "\n")
        return 0

    module = LlvmLoweringBackend(
        TargetProfile(triple=namespace.triple)
    ).lower(artifacts.module)
    toolchain = LlvmToolchainService()
    try:
        if namespace.opt_level:
            module = toolchain.optimize(module, namespace.opt_level)
        if namespace.verify_llvm:
            print(toolchain.verify(module), file=sys.stderr)
        if namespace.emit_object:
            print(
                f"wrote {toolchain.emit_object(module, namespace.emit_object)}",
                file=sys.stderr,
            )
        if namespace.emit_native_assembly:
            sys.stdout.write(toolchain.emit_assembly(module))
        if namespace.emit_llvm:
            sys.stdout.write(module.text)
        if namespace.jit:
            return toolchain.jit_execute(module)
    except LlvmToolchainUnavailable as exc:
        print(f"llvm backend unavailable: {exc}", file=sys.stderr)
        return 3
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
